apiVersion: 1
datasources:
  - name: IT Ops Postgres
    uid: itops-pg
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: $PG_USER
    isDefault: true
    jsonData:
      database: $PG_DB
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: $PG_PASSWORD
